# Generated by Django 4.2.4 on 2023-08-09 14:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('name', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='FailureReason',
            fields=[
                ('reason', models.CharField(max_length=30, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Form',
            fields=[
                ('formNumber', models.IntegerField(max_length=20, primary_key=True, serialize=False)),
                ('date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Recipient',
            fields=[
                ('name', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('phone', models.CharField(max_length=15)),
                ('address', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Package',
            fields=[
                ('tracking', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('weight', models.DecimalField(decimal_places=2, max_digits=5)),
                ('height', models.DecimalField(decimal_places=2, max_digits=5)),
                ('state', models.CharField(choices=[('en_deposito', 'EN_DEPOSITO'), ('en_distribucion', 'EN_DISTRIBUCION')], max_length=15)),
                ('tipo_paquete', models.CharField(choices=[('P', 'Peso Menor a 1000'), ('M', 'Peso Menor a 3000'), ('G', 'Otros')], max_length=1)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sistema_logistica_app.client')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sistema_logistica_app.recipient')),
            ],
        ),
        migrations.CreateModel(
            name='FormItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.IntegerField(max_length=10)),
                ('failureReason', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sistema_logistica_app.failurereason')),
                ('form', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sistema_logistica_app.form')),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sistema_logistica_app.package')),
            ],
            options={
                'unique_together': {('package', 'form', 'position')},
            },
        ),
    ]
