# Generated by Django 4.2.4 on 2023-08-09 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema_logistica_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='package',
            old_name='tipo_paquete',
            new_name='typePackage',
        ),
        migrations.AlterField(
            model_name='form',
            name='formNumber',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='formitem',
            name='position',
            field=models.IntegerField(),
        ),
    ]
