# Generated by Django 4.2.4 on 2023-08-10 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema_logistica_app', '0003_alter_package_tracking'),
    ]

    operations = [
        migrations.AlterField(
            model_name='package',
            name='typePackage',
            field=models.CharField(blank=True, max_length=2),
        ),
    ]
