# Generated by Django 4.2.4 on 2023-08-10 17:25

from django.db import migrations, models
import sistema_logistica_app.enums


class Migration(migrations.Migration):

    dependencies = [
        ('sistema_logistica_app', '0004_alter_package_typepackage'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='classificationAttributes',
            field=models.CharField(choices=[('weight', 'PESO'), ('height', 'ALTURA')], default=sistema_logistica_app.enums.ClassificationAttributes['PESO'], max_length=20),
        ),
    ]
