# Generated by Django 4.2.4 on 2023-08-10 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema_logistica_app', '0006_alter_package_classificationattributes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='package',
            name='classificationAttributes',
        ),
        migrations.RemoveField(
            model_name='package',
            name='recipient',
        ),
        migrations.AddField(
            model_name='package',
            name='classification_attributes',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='package',
            name='recipientAdress',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='package',
            name='recipientName',
            field=models.CharField(default='jasda', max_length=50),
        ),
        migrations.AddField(
            model_name='package',
            name='recipientPhone',
            field=models.CharField(blank=True, max_length=15),
        ),
    ]
