# Generated by Django 4.2.4 on 2023-08-10 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema_logistica_app', '0007_remove_package_classificationattributes_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='package',
            name='recipientName',
            field=models.CharField(max_length=50),
        ),
    ]
