# Generated by Django 4.2.4 on 2023-08-10 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema_logistica_app', '0008_alter_package_recipientname'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='package',
            name='classification_attributes',
        ),
        migrations.AlterField(
            model_name='package',
            name='recipientName',
            field=models.CharField(choices=[('Ivan', 'Ivan')], max_length=50),
        ),
    ]
