# Generated by Django 4.2.4 on 2023-08-10 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema_logistica_app', '0009_remove_package_classification_attributes_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='package',
            name='recipientAdress',
            field=models.CharField(choices=[('Ivan', 'asdasdqweasdqwe')], max_length=100),
        ),
    ]
