# Generated by Django 4.2.4 on 2023-08-10 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema_logistica_app', '0010_alter_package_recipientadress'),
    ]

    operations = [
        migrations.AlterField(
            model_name='package',
            name='recipientAdress',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='package',
            name='recipientName',
            field=models.CharField(choices=[('Ivan', 'Ivan'), ('Carlos', 'Carlos')], max_length=50),
        ),
    ]
