# Generated by Django 4.2.4 on 2023-08-11 18:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sistema_logistica_app', '0013_alter_formitem_package'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formitem',
            name='failureReason',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='sistema_logistica_app.failurereason'),
        ),
    ]
