# Generated by Django 4.2.4 on 2023-08-11 18:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sistema_logistica_app', '0015_alter_formitem_unique_together_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='package',
            old_name='recipientAdress',
            new_name='recipientAddress',
        ),
    ]
