# Generated by Django 4.2.4 on 2023-08-11 19:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sistema_logistica_app', '0016_rename_recipientadress_package_recipientaddress'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='package',
            name='recipientAddress',
        ),
        migrations.RemoveField(
            model_name='package',
            name='recipientName',
        ),
        migrations.RemoveField(
            model_name='package',
            name='recipientPhone',
        ),
        migrations.AddField(
            model_name='package',
            name='recipient',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='sistema_logistica_app.recipient'),
            preserve_default=False,
        ),
    ]
