# Generated by Django 4.2.4 on 2023-08-12 16:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sistema_logistica_app', '0017_remove_package_recipientaddress_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formitem',
            name='failureReason',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='sistema_logistica_app.failurereason'),
        ),
    ]
