# Generated by Django 4.2.1 on 2023-08-15 11:15

from django.db import migrations, models
import django.utils.timezone
import sistema_logistica_app.enums
import sistema_logistica_app.models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema_logistica_app', '0018_alter_formitem_failurereason'),
    ]

    operations = [
        migrations.AlterField(
            model_name='form',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='form',
            name='formNumber',
            field=models.IntegerField(default=sistema_logistica_app.models.getAmountForms, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='package',
            name='state',
            field=models.CharField(choices=[('en_deposito', 'EN_DEPOSITO'), ('en_distribucion', 'EN_DISTRIBUCION')], default=sistema_logistica_app.enums.StatesEnum['EN_DEPOSITO'], max_length=15),
        ),
    ]
